In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,...,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Platinum Rewards,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,0,Ишимбай,NaN,0.0,Договор на текущий счет для дебетовой карты,...,VISA Classic,2019.0,NaN,0.0,0,1900.0,1000.0,6200.0,3000.0,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,0,Юрга,NaN,0.0,Договор на текущий счет для дебетовой карты,...,NaN,NaN,NaN,0.0,0,0.0,0.0,0.0,0.0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Rewards,2021.0,NaN,24300.0,118,0.0,0.0,35400.0,35400.0,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Eurocard/MasterCard World,2018.0,2022.0,24300.0,118,0.0,0.0,35400.0,35400.0,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,0,Пятигорск,NaN,200000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,300.0,9900.0,10100.0,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,0,Кемерово,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,15000.0,33,0.0,0.0,15000.0,15000.0,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,0,Санкт-Петербург,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,600.0,5,0.0,0.0,1100.0,1100.0,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,0,Уфа,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,0.0,1100.0,1100.0,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,0,Москва,NaN,30000.0,Кредитная карта,...,NaN,NaN,NaN,9900.0,19,0.0,0.0,29900.0,29900.0,dc

In [22]:
new_data = data.copy().drop('client_id', axis=1)

In [24]:
new_data['client_age'] = 2022 - new_data['birth_date']

In [26]:
new_data['client_age'].mean()

43.594631616624014

In [28]:
new_data[new_data['current_balance_avg_sum'] != 0]

,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,card_id,...,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type,client_age
0,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,a83cbc33f164deae41b3339141923cc7,...,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc,37
1,М,1951,2009-09-24,R,0,Ишимбай,NaN,0.0,Договор на текущий счет для дебетовой карты,8dae17a830bb05d151034df618efbcad,...,2019.0,NaN,0.0,0,1900.0,1000.0,6200.0,3000.0,dc,71
5,Ж,1980,2015-06-19,R,0,Октябрьский,NaN,0.0,Договор на текущий счет для дебетовой карты,e3baaf11e34b13c3cbb93fd6e2f6096e,...,2019.0,NaN,0.0,0,12700.0,1000.0,15000.0,7800.0,dc,42
9,М,1989,2010-12-16,R,0,Туапсе,NaN,0.0,Договор на текущий счет для дебетовой карты,ca3b0bab14de9b04132ecb84c2b01f6c,...,2019.0,NaN,9700.0,33,6100.0,10200.0,13800.0,23500.0,dc,33
10,М,1989,2010-12-16,R,0,Туапсе,NaN,0.0,Договор на текущий счет для дебетовой карты,bae6632af4c6d36013a6a6a594a261d6,...,2021.0,NaN,9700.0,33,6100.0,10200.0,13800.0,23500.0,dc,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371561,М,1990,2022-02-03,N,0,Москва,NaN,0.0,Договор на текущий счет для дебетовой карты,ad3b2e642411178eb49102879d90ca42,...,2022.0,NaN,500.0,3,1500.0,6700.0,12400.0,12200.0,dc,32
371562,М,1976,2014-06-16,R,0,Екатеринбург,NaN,0.0,Договор на текущий счет для дебетовой карты,b1397fb53973dd0dfbebc904d62d4e12,...,2021.0,NaN,1000.0,4,100.0,0.0,30000.0,30000.0,dc,46
371563,Ж,1990,2010-03-09,R,0,Сочи,NaN,0.0,Договор на текущий счет для дебетовой карты,7e84d8c74dc6cf9ef92401134d3aa68b,...,2021.0,NaN,0.0,0,100.0,100.0,0.0,0.0,dc,32
371566,М,1970,2020-06-11,R,0,Уфа,NaN,0.0,Договор на текущий счет для дебетовой карты,dccd72269a1b128a42c18e61f9f70cf6,...,2022.0,NaN,0.0,0,15600.0,15600.0,0.0,0.0,dc,52
371571,М,1977,2007-05-21,R,0,Ейск,NaN,500000.0,Кредитная карта,9416050372d690b3d48d435f6c84e193,...,NaN,NaN,179800.0,8,100.0,0.0,240100.0,239800.0,dc,45

In [30]:
(371583 - 210431) / 371583

0.43369045408428264

In [31]:
new_data['city'].value_counts()

Уфа                 59076
Москва              31072
Краснодар           21470
Санкт-Петербург     12982
Стерлитамак         12454
                    ...
Березники             200
Курганинск            197
Ангарск               191
Языково               131
Николо-Березовка      102
Name: city, Length: 150, dtype: int64